---

- name: Play1
  hosts: webservers
  vars:
    project_name: "tfl"
    project_home: "{{ ansible_env.HOME }}/{{ project_name }}"
    venv_home: "{{ project_home }}/virtualenv"
    repo_url: "https://github.com/dvoong/IOTLaunchpad.git"
    source_path: "{{ project_home }}/source"
    database_user: "{{ project_name }}"
    locale: "en_US.UTF8"
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      sudo: True
      with_items:
        - git
        - postgresql
        - libpq-dev
        - python-virtualenv
        - python-dev
        - python-psycopg2
        - mongodb
    - name: install python packages
      pip: name={{ item }} virtualenv={{ venv_home }}
      with_items:
        - psycopg2
        - twisted
        - pymongo
    - name: check out the repository on the host
      git: repo={{ repo_url }} dest={{ source_path }} accept_hostkey=yes
    - name: Create a db user
      postgresql_user:
        name: "{{ database_user }}"
        password: "{{ lookup('password', 'database_password.txt')}}"
      sudo: True
      sudo_user: postgres
    - name: Create the database
      postgresql_db:
        name: "{{ project_name }}"
        owner: "{{ database_user }}"
        encoding: UTF8
        lc_ctype: "{{ locale }}"
        lc_collate: "{{ locale }}"
        template: template0
      sudo: True
      sudo_user: postgres

#    - name: test
#      ping:
#      notify: test handler
#    - debug: var=ansible_ssh_user
#    - debug: var=ansible_env.HOME
#  handlers:
#    - name: test handler
#      ping:
  